import type { ExtractedItem } from "../domain/types";

export function academicEventFixture(overrides: Partial<ExtractedItem> = {}): ExtractedItem {
  return {
    id: "item-1",
    documentId: "doc-1",
    sourceDocumentIds: ["doc-1"],
    sourceReferences: [{ id: "source-1", documentId: "doc-1", fileName: "sample.pdf", documentType: "syllabus", evidence: "샘플 근거" }],
    title: "보고서",
    itemType: "assignment",
    courseName: "UX 디자인",
    courseCode: null,
    date: "2026-07-23",
    time: "23:59",
    isAllDay: false,
    dateCertainty: "exact-date",
    scheduledWeek: null,
    scheduledWeekLabel: null,
    weekOneStartDate: null,
    classMeetingTimes: [],
    assignmentType: "report",
    examType: null,
    workload: "보고서 5쪽",
    requirements: "수업 자료를 바탕으로 보고서를 작성",
    researchNeeded: "unknown",
    deliverableComplexity: null,
    examScope: null,
    gradingMethod: null,
    submissionMethod: "LMS",
    requiredMaterials: "PDF",
    difficulty: "high",
    estimatedDurationMinutes: 180,
    confidence: .8,
    uncertaintyNotes: [],
    confirmationStatus: "confirmed",
    confirmationIssues: [],
    revision: 1,
    updateNoticeStatus: "reviewed",
    updatedAt: "2026-07-18T12:00:00.000Z",
    reviewStatus: "needs-review",
    isUserEdited: false,
    ...overrides,
  };
}
